### PR TITLE
Delete Profile Card directory

### PR DESCRIPTION
**Pull request by ayushi-ras**
I want to send it seperate

### CODE REVIEW

**Comment by avincodes** [comment]
Nope okay I think you have made the changes to a new PR not the previous one, what you can do is, close all of them and make two PRs for the two projects?

**Comment by ayushi-ras** [comment]
ok

**Comment by ayushi-ras** [comment]
let it be like that , i will contribute some more

**Comment by avincodes** [comment]
@ayushi-ras yes I won't be marking these as spam! Simply make two separate pull requests to this repo and Ill be happy to merge them! And are you a beginner to GitHub? If so, ill be happy to help if you can drop me a message on Discord on the Hacktoberfest server or through DMs Avin#9023!

**Comment by ayushi-ras** [comment]
Thanks , yes I am a beginner in GitHub as well as in hacktoberfest

**Pull request closed without merging**
