### PR TITLE
Added index.js

### PR DESCRIPTION
**Pull request by Sowham-3098**
Added this index.js for issue #28

### CODE REVIEW

**Comment by avincodes** [comment]
Refrain from opening multiple pull requests for the same snippet.

**Comment by Sowham-3098** [comment]
Please delete the spam level. Otherwise I will never be participated in Hacktoberfest. Please @avincodes .

**Comment by Sowham-3098** [comment]
> Refrain from opening multiple pull requests for the same snippet.

I am sorry for this. Please help me and please delete the spam level

**Comment by Sowham-3098** [comment]
Can you please remove the duplicate lebels?

**Pull request closed without merging**
