### PR TITLE
Added scroll-to-top button feature

### PR DESCRIPTION
**Pull request by DEV-Dhruva**
Hey @avincodes , I have added a scroll-to-top button feature snippet in your repository.  So, kindly check it and review it also please accept/merge my pull request. 
Thank you.

### CODE REVIEW

**Comment by avincodes** [comment]
Please add a readme file wth some details of your snippet and a screenshot of it.

**Review by avincodes — CHANGES_REQUESTED** [review]
Please add a readme file wth some details of your snippet and a screenshot of it.

**Review by avincodes — APPROVED** [review]
Good to go!

**Comment by DEV-Dhruva** [comment]
> Good to go!

Hey @avincodes , will you please assign me the label of hacktoberfest 2022 .

**Comment by avincodes** [comment]
@DEV-Dhruva sure, I forgot, im sorry!

**Comment by DEV-Dhruva** [comment]
Thank you @avincodes

**Pull request merged**
