### PR TITLE
Added Live weather Web Page

### PR DESCRIPTION
**Pull request by AbhishekKumar2002**
I have added Live Weather Web Page. I request you to check it and kindly accept my PR.

### CODE REVIEW

**Review by avincodes — COMMENTED** [review]
Please add a readme file that contains an introduction to your snippet as well as screen shot or a recording of the snippet in action

**Comment by AbhishekKumar2002** [comment]
Sir I have added Readme.md file and attached screenshot to it.

**Review by avincodes — APPROVED** [review]
Perfect!

**Comment by avincodes** [comment]
Great work, thank you @AbhishekKumar2002!

**Comment by avincodes** [comment]
Happy to! 🙌 Do check out my other repos if you wanna contribute there as well!

**Pull request merged**
