### PR TITLE
Added a e-commerce website

### PR DESCRIPTION
**Pull request by abhityagi09**

### CODE REVIEW

**Comment by avincodes** [comment]
Hey, @abhityagi09 thank you for the pull request! 

Please add a readme file including some basic information about your snippet as well as some screenshots of your snippet working.

**Comment by avincodes** [comment]
Please add a screenshot as well @abhityagi09

**Comment by abhityagi09** [comment]
> Please add a screenshot as well @abhityagi09 

I have added a screenshot in readme file

**Comment by avincodes** [comment]
Accepted!

**Pull request merged**
